## NumPy Arrays

In [3]:
import numpy as np

In [5]:
mylist = [1,2,3]
type(mylist)

list

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
mylist

[1, 2, 3]

In [8]:
myarr = np.array(mylist)

In [9]:
type(myarr)

numpy.ndarray

In [10]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.random.rand(1)

array([0.29653246])

In [23]:
np.random.rand(5,2)

array([[0.96902796, 0.17693877],
       [0.03691315, 0.72380129],
       [0.87094486, 0.18500462],
       [0.80169543, 0.13216384],
       [0.08902011, 0.7842119 ]])

In [24]:
np.random.randn(10)

array([ 0.35472254, -0.88924543,  0.71569684,  2.00180269,  0.13618566,
       -0.3300904 , -1.3566638 , -0.17483052, -0.84938533, -0.0961973 ])

In [25]:
np.random.randn(4,5)

array([[ 1.28842275,  0.69244066,  0.31727197, -1.24444642, -1.5905552 ],
       [-1.04609368, -0.29205931,  0.50708077,  0.51209598,  2.04642239],
       [-0.50897537,  1.29623242,  0.68736109, -1.78972114,  0.76201468],
       [-0.98364432,  0.58181896, -1.30315856,  1.01639222,  1.31029221]])

In [26]:
np.random.randint(0, 111, 10)

array([83, 54,  5, 37, 23, 16, 19, 81, 38, 20])

In [27]:
np.random.randint(0,1000,(10,10))

array([[973, 773, 303, 776, 714, 686, 182, 512, 416, 817],
       [299, 233, 107,  26, 987, 436, 791, 782,  97, 523],
       [ 42, 184, 649, 520, 185,  58, 381, 632, 417, 989],
       [740, 705, 187, 379, 500, 233, 273, 469, 976, 201],
       [934, 520, 661, 238,  54, 664, 764, 376, 666, 176],
       [277, 213, 615, 749, 560, 584, 183, 721,  70, 114],
       [837,  65, 525,  20, 951, 577,  90, 823, 558,  28],
       [101, 813, 872, 308, 485, 229, 184, 521, 279, 306],
       [703, 814,  73, 672,  71,  58,   1, 438, 424, 522],
       [737, 140, 211, 185, 875,  92, 866, 230, 663, 136]])

In [28]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [29]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [30]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
ranarr = np.random.randint(0,101,10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [32]:
ranarr.max()

99

In [33]:
ranarr.min()

2

In [34]:
ranarr.argmax()

5

In [35]:
ranarr.argmin()

7

In [36]:
ranarr.dtype

dtype('int64')

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [38]:
arr.shape

(25,)

In [39]:
arr = arr.reshape(5,5)

In [40]:
arr.shape

(5, 5)

## Indexing and selection

In [41]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
arr[8]

8

In [43]:
arr[1:5]

array([1, 2, 3, 4])

In [44]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr[0:5] = 100

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr = np.arange(0,11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
slice_of_arr = arr[0:5]

In [53]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [54]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [55]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [56]:
arr_copy = arr.copy()

In [57]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [58]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [59]:
arr_2d = np.array([[5, 10, 15], [20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [60]:
arr_2d.shape

(3, 3)

In [61]:
arr_2d[0]

array([ 5, 10, 15])

In [62]:
arr_2d[-1]

array([35, 40, 45])

In [63]:
arr_2d[1][1]

25

In [64]:
arr_2d[1,1]

25

In [65]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [66]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [68]:
arr = np.arange(1,11)

In [69]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [70]:
bool_arr = arr>4

In [71]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [72]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [73]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

## Operations

In [74]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [77]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [78]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [79]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
arr / arr

/var/folders/94/b1tt0kzs1975xbbmjtf99tkc0000gn/T/ipykernel_23331/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [82]:
1 / arr

/var/folders/94/b1tt0kzs1975xbbmjtf99tkc0000gn/T/ipykernel_23331/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [83]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [84]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [85]:
np.log(arr)

/var/folders/94/b1tt0kzs1975xbbmjtf99tkc0000gn/T/ipykernel_23331/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [86]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arr.sum()

45

In [88]:
arr.mean()

4.5

In [89]:
arr.max()

9

In [90]:
arr.var()

8.25

In [91]:
arr.std()

2.8722813232690143

In [93]:
arr2d = np.arange(0,25).reshape(5,5)

In [94]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [95]:
arr2d.sum()

300

In [96]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [97]:
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])